" All system-wide defaults are set in $VIMRUNTIME/debian.vim (usually just
" /usr/share/vim/vimcurrent/debian.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vim/vimrc), since debian.vim will be overwritten 
" everytime an upgrade of the vim packages is performed.  It is recommended to 
" make changes after sourcing debian.vim since it alters the value of the 
"'compatible' option.
" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous 
" options, so any other options should be set AFTER setting 'compatible'.  
"set compatible 
" Vim5 and later versions support syntax highlighting. Uncommenting the next 
" line enables syntax highlighting by default.  syntax on

set expandtab 
set shiftwidth=2 
set softtabstop=2 
" Uncomment next line to enable line numbers
set nu

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif
" Fixing backspace problem "
set backspace=2

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"if has("autocmd")
"  filetype plugin indent on
"endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif


" Loading ctrlp plugin"
set runtimepath^=~/.vim/bundle/ctrlp.vim


" STATUS BAR "
set laststatus=2

set statusline=  	" clean status line"
set statusline=%t       "tail of the filename
set statusline+=[%{strlen(&fenc)?&fenc:'none'}, "file encoding
set statusline+=%{&ff}] "file format
set statusline+=%h      "help file flag
set statusline+=%m      "modified flag
set statusline+=%r      "read only flag
set statusline+=%y      "filetype
set statusline+=%=      "left/right separator
set statusline+=%c,     "cursor column
set statusline+=%l/%L   "cursor line/total lines
set statusline+=\ %P    "percent through file

" PATHOGEN "
execute pathogen#infect()
execute pathogen#helptags()

"" OMNI COMPLETION "
filetype plugin on
" set autocomplete popup menu colors "
highlight Pmenu ctermbg=white gui=bold  
set completeopt-=preview " disable split window "
if has("autocmd") 
  autocmd Filetype java setlocal omnifunc=javacomplete#Complete 
  autocmd Filetype c setlocal omnifunc=syntaxcomplete#Complete
  autocmd Filetype c++ setlocal omnifunc=syntaxcomplete#Complete
  autocmd Filetype cpp setlocal omnifunc=syntaxcomplete#Complete
endif 

let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'

" Use this option to change the mapping to invoke CtrlP in |Normal| mode: > "
let g:ctrlp_map = '<c-p>'


" Set the default opening command to use when pressing the above mapping: > "
let g:ctrlp_cmd = 'CtrlP'

"vim airline "
let g:airline_powerline_fonts = 1
let g:airline_theme = 'powerlineish'

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
syntax enable
set background=dark
"" let g:solarized_termcolors=256
"set t_Co=256
"colorscheme solarized 
colorscheme tomorrow-night-bright
"colorscheme base16-default 
set t_ut=
"let g:solarized_visibility = "high"
"let g:solarized_bold = 1
"let g:solarized_italic = 1
"let g:solarized_contrast = "high"
call togglebg#map("<F5>")


" delimitMate options "
let b:delimitMate_expand_cr = 1
"let b:delimitMate_expand_space = 1

" Indent Options "
autocmd FileType c setlocal autoindent cindent 

" Ruby indentation from http://ubuntuforums.org/showthread.php?t=290462
if has ("autocmd")
    filetype indent on
endif
